# Generated by Django 3.2.11 on 2022-01-25 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
